name: Security Jobs

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 500
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
      
    - name: Build with dotnet
      run: dotnet build --configuration Release

    # SUCCESS
    - name: Dependency Check Scan
      uses: sburris/dependency-check-action@v0.1-beta
      with:
        Project-Name: TestApp
        # The directory path specified here is specific to inside the docker container
        Report-Location: /github/workspace/dcReports
        Report-Format: HTML
        Log-Name: sca-report.txt
             
    # SUCCESS (to be used with above action)
    - name: Upload report artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dcReports
        # This directory path is pointing to the same logical directory above but 
        # outside the docker container
        path: ${{ github.workspace }}/dcReports
             

      # Software Composition Analysis (SCA)
    - name: Snyk
      uses: snyk/actions/dotnet@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Truffle Hog for Secrets Scan
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
      with:
          scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" # Add custom options here*

     #https://github.com/evanextreme/detect-secrets-action
    - name: Detect Secrets
      uses: evanextreme/detect-secrets-action@1.0.0
